name: Pull Request

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  experiment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - run: |
        echo "Running in sffortytwo/forkable"
        git branch
        ls -la
        echo "The secret is [${{ secrets.SUPER_SECRET }}]"
        if [ "${{ secrets.SUPER_SECRET }}" == "Abracadabra" ]; then
          echo "Matched the secret"
        fi

    - run: sh ./runme.sh
