name: Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  experiment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: |
        echo "Running in sffortytwo/forkable"
        echo "On branch ${{ github.event.pull_request.head.ref }}"
        ls -la
        echo "The secret is [${{ secrets.SUPER_SECRET }}]"
        if [ "${{ secrets.SUPER_SECRET }}" == "Abracadabra" ]; then
          echo "Matched the secret"
        fi
